call dein#add('airblade/vim-gitgutter')
call dein#add('gregsexton/gitv')
call dein#add('junegunn/gv.vim', { 'depends': 'vim-fugative' })
call dein#add('mattn/gist-vim')
call dein#add('tpope/vim-fugitive')
call dein#add('tpope/vim-git')
