call dein#add('easymotion/vim-easymotion')
call dein#add('haya14busa/incsearch-easymotion.vim', { 'depends': ['incsearch', 'vim-easymotion'] })
call dein#add('haya14busa/incsearch.vim')
call dein#add('haya14busa/vim-asterisk')
call dein#add('skwp/greplace.vim')
